// This file is auto-generated by scripts/generate-mdx-index.js
// Do not edit manually - your changes will be overwritten!
// To add a new article, create a .mdx file in /content/writing/ and run: npm run generate:mdx

// Sorted article list (newest first) - extracted from MDX frontmatter
export const articleList: { id: string; title: string; date: string }[] = [
  { id: 'event-sourcing', title: 'Event Sourcing Architecture', date: '07.MAY.2026' },
  { id: 'docker-for-developers', title: 'Docker for developers', date: '13.Apr.2026' },
  { id: 'real-time-systems', title: 'Real-Time Systems — Quick Notes', date: '11.Apr.2026' },
  { id: 'oauth-and-pkce', title: 'OAuth & PKCE', date: '10.Apr.2026' },
  { id: 'deploy-frontend-on-aws', title: 'Deploy Frontend on AWS', date: '20.Mar.2026' },
  { id: 'rate-limiting', title: 'Rate Limiting', date: '17.Mar.2026' },
  { id: 'system-design-for-beginners', title: 'System Design For Beginners', date: '14.Mar.2026' },
  { id: 'i-built-my-own-analytics-tool', title: 'I Built My Own Analytics Tool. Here\'s How and Why.', date: '13.Mar.2026' },
  { id: 'reverse-engineering', title: 'Reverse Engineering', date: '022.Feb.2026' },
  { id: 'building-before-you-feel-ready', title: 'Building Before You Feel Ready', date: '21.Feb.2026' },
];
